# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0ef4e01e88ac252240ba6929c53151e8e2c0d2b046d14a5f6c705fff0616e05d0efdd0558a1adf7a6db65d39e268e207ea1094d8892480d392cfe4f64059312

test:
  secret_key_base: 63308ae3ae52bd27d54882aec1da7edb610771084b0a53b9601121959659583274890d238e24efa9a751c1663dc222a5905bfcd254054597b555053f8f7771bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
